export enum ApiRequestTypes {
  ABILITY_SCORE = "ability-scores",
  ALIGNMENT = "alignments",
  BACKGROUND = "backgrounds",
  CONDITION = "conditions",
  DAMAGE_TYPE = "damage-types",
  EQUIPMENT = "equipment",
  EQUIPMENT_CATEGORIES = "equipment-categories",
  FEATURE = "features",
  MAGIC_ITEM = "magic-items",
  MONSTER = "monsters",
  PROFICIENCY = "proficiencies",
  RACE = "races",
  SKILL = "skills",
  SPELL = "spells",
  SUB_RACE = "subraces",
  TRAIT = "traits",
}
